# Generated by Django 4.1.6 on 2023-02-07 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.employee')),
            ],
        ),
    ]
